sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        error_types: 'E_ALL & ~E_NOTICE'
        environment: '%env(SENTRY_ENVIRONMENT)%'
        in_app_exclude:
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%/vendor'
        excluded_exceptions: #exclude validation errors
            - App\Exception\UserNotFoundException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
