version: "3"
services:
  acud2backend:
    image: acud2backend
    build:
      context: ""
      dockerfile: .docker/dev.Dockerfile
    ports:
      - 8080:80
    links:
      - acud-2-mariadb
    volumes:
      - ..:/srv/app:delegated

  acud-2-mariadb:
    image: mariadb:10.4.13
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: acud
      MYSQL_USER: app
      MYSQL_PASSWORD: password
